@startuml func-quad-form
!include plantuml.puml

hide circle
class "y = a(x - p)^2 + q" as 標準形 <<標準形>> {
	+ <b>頂点は点(p, q)</b>
	+ <b>軸は直線x = p</b>
	+ y=ax^2のグラフをx軸方向にp、
	y軸方向にqだけ平行移動したもの
	--
	+ <b>頂点</b>や<b>軸</b>を求める
	+ 頂点や軸から方程式を決定
	+ <b>最大値</b>・<b>最小値</b>を求める
	+ 最大値・最小値から方程式を決定
	+ <b>グラフ</b>を描く
}
class "y = ax^2 + bx + c"  as 一般形 <<一般形>> {
	+ 頂点は点(-b/2a, - (b^2 - 4ac)/4a)
	+ 軸は直線x = -b/2a
	--
	+ 2次方程式の解の判別式を用いる
	+ グラフが通る<b>3点</b>から方程式を決定
}

class "y = a(x - β)(x - γ)" as 因数分解形 <<因数分解形>> {
	+ 軸は直線x = (β+γ)/2
	+ <b>x軸との交点はx = β, γ</b>
	--
	+ <b>x軸との交点</b>を求める
	+ x軸との交点から方程式を決定
	+ 2次<b>方程式</b>・2次<b>不等式</b>を解く
}

標準形 --> 一般形: 展開
一般形 -left-> 標準形: 平方完成
一般形 -right-> 因数分解形: 因数分解
因数分解形 --> 一般形: 展開


@enduml
